---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ithorgrim.
--- DateTime: 18/03/2022 22:59
---
---
local Paragon = require("paragon")

if (not Paragon.Config.QuestGiveExp) then
    return false
end

local function GiveQuestExp(eventid, delay, repeats, player)
    local qData = player:GetData("paragon_quest_index")
    local paragon = player:GetData("paragon")
    for data_key, quest_id in pairs(qData) do
        local pQuest = player:HasQuest(quest_id)
        if (not pQuest) then
            local qExp = Paragon.ServerInformations.quest_informations[quest_id]
            paragon:SetExp(qExp)
            player:SendNotification("Tu as gagné : "..qExp)
        end
    end
end

local function OnPlayerGiveExp(event, player, amount, object)
    local pLevel = player:GetLevel()
    if (not object and Paragon.Config.MinPlayerLevelQuestGiveExp >= pLevel) then
        local _temp = {}
        for quest_id, quest_exp in pairs(Paragon.ServerInformations.quest_informations) do
            local pQuest = player:HasQuest(quest_id)
            if (pQuest) then
                _temp[#_temp + 1] = quest_id
            end
        end
        player:SetData("paragon_quest_index", _temp)
        player:RegisterEvent(GiveQuestExp, 1000, 1)
    end
end
RegisterPlayerEvent(12, OnPlayerGiveExp)