---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ithorgrim.
--- DateTime: 19/03/2022 22:31
---
local Paragon = require("paragon")
if (Paragon.Config.Type == 2) then
    return false
end

local function GetFirstPage()
    local min
    for _, gossipData in pairs(Paragon.ServerInformations.gossip_informations) do
        if (not min) then
            min = gossipData.menu_id
        else
            if (min > gossipData.menu_id) then
                min = gossipData.menu_id
            end
        end
    end
    return min
end

local function GetSpecificPage(event, player, object, page)
    player:GossipClearMenu()
    for _, gossipData in pairs(Paragon.ServerInformations.gossip_informations) do
        if (gossipData.menu_id == page) then
            if (gossipData.action_type == 0) then
                player:GossipMenuAddItem(0, gossipData.option_text, gossipData.action_type, gossipData.action_id, true, "Combien de point souhaitez vous ajouter / supprimer")
            else
                player:GossipMenuAddItem(0, gossipData.option_text, gossipData.action_type, gossipData.action_id)
            end
        end
    end
end

local function OnGossipHello(event, player, object)
    local page = GetFirstPage()
    GetSpecificPage(event, player, object, page)

    player:GossipSendMenu(1, player, 123)
end
RegisterCreatureGossipEvent(197, 1, OnGossipHello)

local function OnGossipSelect(event, player, object, option_type, option_id, points)
    local paragon = player:GetData("paragon")

    if (option_type == 0) then
        local add = false
        points = tonumber(points)

        if (points > 0) then
            add = true
        end

        if (paragon:SetSpellPoint(option_id, points, add)) then
            player:SendNotification("Vos points on bien été attribués")
            player:SetParagonAura(option_id)
        else
            player:SendNotification("Pas bon")
        end

    elseif (option_type == 1) then
        GetSpecificPage(event, player, object, option_id)
        player:GossipSendMenu(1, player, 123)

    elseif(option_type == 2) then
        local paragon = player:GetData("paragon")
        paragon:Method(option_id)
    end
end
RegisterPlayerGossipEvent(123, 2, OnGossipSelect)