---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ithorgrim.
--- DateTime: 18/03/2022 18:51
---
local Paragon = {}

function Paragon.OnPlayerLogin(event, player)
    player:SetParagon()
    player:SetAllParagonAura()
end
RegisterPlayerEvent(3, Paragon.OnPlayerLogin)

function Paragon.OnServerReload(event)
    for _, player in ipairs(GetPlayersInWorld()) do
        Paragon.OnPlayerLogin(event, player)
    end
end
RegisterServerEvent(33, Paragon.OnServerReload)

return Paragon