---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ithorgrim.
--- DateTime: 17/03/2022 11:10
---

local Paragon = require("paragon")
    Paragon.Config = { }

--[[
    TODO : Change comments bellow
]]--
    --[[-----------------------------------------------------------------------------------------------]]--
    -- Points Per Level
    --
    --    Paragon.Database
    --        Description: The number of points to be given must remain an integer
    --        Important:   The number of points per level can be an integer or a float, it must always be greater than 0
    --        Default:     2
    --
    --        Note: The calculation will be (Paragon Level * Point Per Level)
    --[[-----------------------------------------------------------------------------------------------]]--

Paragon.Config.Database = "r1_eluna"

--[[-----------------------------------------------------------------------------------------------]]--
-- Points Per Level
--
--    Paragon.PointPerLevel
--        Description: The number of points to be given must remain an integer
--        Important:   The number of points per level can be an integer or a float, it must always be greater than 0
--        Default:     2
--
--        Note: The calculation will be (Paragon Level * Point Per Level)
--[[-----------------------------------------------------------------------------------------------]]--

Paragon.Config.PointPerLevel = 2

--[[-----------------------------------------------------------------------------------------------]]--
-- Max Level
--
--    Paragon.MaxLevel
--        Description: The maximum number of Paragon Level
--        Important:   The level cannot be higher than 2^32 (4 294 967 296)
--        Default:     4294967296
--
--[[-----------------------------------------------------------------------------------------------]]--

Paragon.Config.MaxLevel = 4294967296

--[[-----------------------------------------------------------------------------------------------]]--
-- Max Spell Points
--
--    Paragon.MaxSpellPoints
--        Description: The maximum number of points per spell
--        Important:   The maximum number of points per spell cannot exceed 255
--        Default:     255
--
--[[-----------------------------------------------------------------------------------------------]]--

Paragon.Config.MaxSpellPoints = 255

--[[
    TODO : Change comments bellow
]]--
    --[[-----------------------------------------------------------------------------------------------]]--
    -- Max Spell Points
    --
    --    Paragon.MaxSpellPoints
    --        Description: The maximum number of points per spell
    --        Important:   The maximum number of points per spell cannot exceed 255
    --        Default:     true (false : Desactivate | true : Active (populate paragon_quest for exp))
    --
    --[[-----------------------------------------------------------------------------------------------]]--

Paragon.Config.QuestGiveExp = false

    --[[-----------------------------------------------------------------------------------------------]]--
    -- Max Spell Points
    --
    --    Paragon.MaxSpellPoints
    --        Description: The maximum number of points per spell
    --        Important:   The maximum number of points per spell cannot exceed 255
    --        Default:     1 ()
    --
    --[[-----------------------------------------------------------------------------------------------]]--

Paragon.Config.MinPlayerLevelQuestGiveExp = 1

    --[[-----------------------------------------------------------------------------------------------]]--
    -- Max Spell Points
    --
    --    Paragon.MaxSpellPoints
    --        Description: The maximum number of points per spell
    --        Important:   The maximum number of points per spell cannot exceed 255
    --        Default:     500 (populate paragon_quest for individual quest exp)
    --
    --[[-----------------------------------------------------------------------------------------------]]--

Paragon.Config.UniversaleQuestExp = 500

--[[
    TODO : Change comments bellow
]]--
    --[[-----------------------------------------------------------------------------------------------]]--
    -- Max Spell Points
    --
    --    Paragon.MaxSpellPoints
    --        Description: The maximum number of points per spell
    --        Important:   The maximum number of points per spell cannot exceed 255
    --        Default:     true (false : Desactivate | true : Active (populate paragon_quest for exp))
    --
    --[[-----------------------------------------------------------------------------------------------]]--

Paragon.Config.CreatureGiveExp = true

    --[[-----------------------------------------------------------------------------------------------]]--
    -- Max Spell Points
    --
    --    Paragon.MaxSpellPoints
    --        Description: The maximum number of points per spell
    --        Important:   The maximum number of points per spell cannot exceed 255
    --        Default:     1 ()
    --
    --[[-----------------------------------------------------------------------------------------------]]--

Paragon.Config.MinPlayerLevelCreatureGiveExp = 1

    --[[-----------------------------------------------------------------------------------------------]]--
    -- Max Spell Points
    --
    --    Paragon.MaxSpellPoints
    --        Description: The maximum number of points per spell
    --        Important:   The maximum number of points per spell cannot exceed 255
    --        Default:     500 (populate paragon_quest for individual quest exp)
    --
    --[[-----------------------------------------------------------------------------------------------]]--

Paragon.Config.UniversaleCreatureExp = 500

    --[[-----------------------------------------------------------------------------------------------]]--
    -- Max Spell Points
    --
    --    Paragon.MaxSpellPoints
    --        Description: The maximum number of points per spell
    --        Important:   The maximum number of points per spell cannot exceed 255
    --        Default:     500 (populate paragon_quest for individual quest exp)
    --
    --[[-----------------------------------------------------------------------------------------------]]--

Paragon.Config.PlayerCreatureLevelDifference = 3